version: '2'

services:
  couch-db:
    image: couchdb
    restart: always
    ports:
      - "5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
        - ./dbdata:/opt/couchdb/data
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/www/data/static
    links:
      - node1:node1
      - node2:node2
    depends_on:
      - node1
      - node2
    ports:
      - "8080:80"
    networks:
      - app-network

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules 
    ports:
      - "3000"
    environment:
      - COUCHDB_URL=couch-db:5984
      - INSTANCE=node1
    networks:
      - app-network

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "3000"
    environment:
      - COUCHDB_URL=couch-db:5984
      - INSTANCE=node2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
